# Generated by Django 2.2.5 on 2019-09-24 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mexicantreasure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='has_active_session',
        ),
        migrations.AlterField(
            model_name='player',
            name='friends',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mexicantreasure.Player'),
        ),
    ]
