# Generated by Django 2.2.5 on 2019-09-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mexicantreasure', '0003_remove_player_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_status',
        ),
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
